### PR TITLE
Fixed README.md

### PR DESCRIPTION
**Pull request by ekschro**
There seemed to be js code blocks that were opened and closed in the wrong areas.  This resulted in the literal MarkDown syntax being printed.

### CODE REVIEW

**Comment by tunnckoCore** [comment]
Thanks for this. But the thing is that the readme is auto-generated from .verb.md plus actual source code comments. So, the bug is probably because it's tricky to write markdown in a code comment.

So the changes should be done in the code comments instead of the readme.

**Comment by ekschro** [comment]
I see 😂 That completely went over my head.

**Comment by ekschro** [comment]
**Issue**
So, the issue was the the jsdoc examples found in the literal jsdoc in `index.js` were breaking the Verb generated MarkDown.  This was because the jsdoc examples were not enclosed in block comments.

**Solution**
Block comments were not working inside the MarkDown JS code blocks... So I simply used single line comments!

**Comment by tunnckoCore** [comment]
I don't think it's better. It's quite obvious what it shows currently in the readme, no matter the syntax highlighting problems.

**Comment by ekschro** [comment]
I thought it at least avoided the corruption of the **About** section... But I understand.

**Pull request closed without merging**
